### PR TITLE
Update manualchoiupgrade.rst

### PR DESCRIPTION
**Pull request by designgears**
Well, wasn't sure how to word that, but this is how I fix it and is mentioned in the gbatemp thread that originally detailed this method.

### CODE REVIEW

**Comment by noahc3** [comment]
What is probably happening is an INI conflict with the old format Choi produces and newer Hekate. Going to close this as a better solution is just providing a working INI in the guide.

**Comment by designgears** [comment]
I doubt that is the case, I've been stuck in this boat a couple of times, I used the current version of Hekate with my working INI and it still didn't boot. I booted atmosphere with fusee-primary, and sxos, all with the same result. It wasn't until I found the info about reinx being able to properly boot that I tried it and has worked on several occasions.

**Comment by tumGER** [comment]
I have downgraded six times by now and never had to use ReiNX, this is purely caused by ChoiNX not being updated and thus creating useless hekate-ipl.ini's in the wrong directory

**Comment by designgears** [comment]
@tumGER  ChoiNX works great, never had an issue downgrading with it, I'm talking about the non-homebrew app and very manual downgrade/upgrade process.

**Comment by tumGER** [comment]
Oops accidentally switched issues in my head. I used Choi to downgrade and never had to use ReiNX.

**Comment by designgears** [comment]
> Oops accidentally switched issues in my head. I used Choi to downgrade and never had to use ReiNX.

Np, sometimes it works fine, just felt it was worth mentioning, check out the gbatemp thread, it's used pretty often.

**Comment by noahc3** [comment]
If you're using your working INI then you aren't loading the nocmac kip are you?

**Comment by designgears** [comment]
> If you're using your working INI then you aren't loading the nocmac kip are you?

I mean putting the boot option into my own INI, it's also completely fine to drop it in the ini folder on its own. Nothing wrong with the INI generated by Choi.

`[config]
autoboot=0
autoboot_list=0
bootwait=5
customlogo=0
verification=1
backlight=100
autohosoff=0
autonogc=1

[FS_610-exfat_nocmac_nogc]
kip1=FS600-exfat_nocmac_nogc.kip1

[ATMOS]
payload=atmosphere/fusee-primary.bin
kip1patch=nosigchk
atmosphere=1

[Stock]
payload=atmosphere/fusee-primary.bin
stock=1`

**Comment by noahc3** [comment]
yea that profile format is out of date. it needs to be in the format

[FS_610-exfat_nocmac_nogc]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
atmosphere=1
kip1=FS600-exfat_nocmac_nogc.kip1

for a kosmos based setup

**Comment by designgears** [comment]
If I was loading fusee-secondary you would be correct, but since I like all the patches to load I use payload and point to fusee-primary.

**Comment by noahc3** [comment]
Appreciate that :)

**Comment by designgears** [comment]
Alright, finally got around to finishing this up, I can confirm that does work and should definitely be included in the guide! How it's written now is guaranteed to fail on first boot.

**Comment by noahc3** [comment]
I'll get this done ASAP, thanks for testing

**Pull request closed without merging**
